# Publish all images in the docker-compose.yml in the GitHub mirror at:
# https://github.com/montehurd?tab=packages&repo_name=mediawiki-docker-images

name: Build Docker images for docker-compose.yml services

on:
  push:
    branches:
      - main

permissions: 
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images
        env:
          REGISTRY: ghcr.io/${{ github.repository }}/
        run: |
          docker compose build
          docker compose push
